# Generated by Django 6.0.1 on 2026-02-16 23:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom ')),
                ('contact_urgence_nom', models.CharField(max_length=100, verbose_name="Nom du contact d'urgence")),
                ('contact_urgence_telephone', models.CharField(max_length=20, verbose_name="Téléphone du contact d'urgence")),
                ('contact_urgence_lien', models.CharField(max_length=100, verbose_name='Lien avec le client')),
                ('date_inscription', models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date d'inscription")),
                ('est_actif', models.BooleanField(default=True, verbose_name='Client actif')),
                ('est_blackliste', models.BooleanField(default=False, verbose_name='Blacklisté')),
                ('date_blacklist', models.DateTimeField(blank=True, null=True, verbose_name='Date de blacklist')),
                ('raison_blacklist', models.TextField(blank=True, verbose_name='Raison de la blacklist')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to=settings.AUTH_USER_MODEL, verbose_name='Agent assigné')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients_crees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['-date_inscription'],
            },
        ),
        migrations.CreateModel(
            name='DocumentClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_document', models.CharField(choices=[('CONTRAT_TRAVAIL', 'Contrat de travail'), ('BULLETIN_SALAIRE', 'Bulletin de salaire'), ('AVIS_IMPOSITION', "Avis d'imposition"), ('FACTURE', 'Facture'), ('JUSTIFICATIF_DOMICILE', 'Justificatif de domicile'), ('RELEVE_BANCAIRE', 'Relevé bancaire'), ('AUTRE', 'Autre document')], max_length=50, verbose_name='Type de document')),
                ('nom_fichier', models.CharField(max_length=255, verbose_name='Nom du fichier')),
                ('fichier', models.FileField(upload_to='clients/documents/%Y/%m/', verbose_name='Fichier')),
                ('date_upload', models.DateTimeField(auto_now_add=True, verbose_name="Date d'upload")),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='bank.client')),
            ],
            options={
                'verbose_name': 'Document client',
                'verbose_name_plural': 'Documents clients',
                'ordering': ['-date_upload'],
            },
        ),
        migrations.CreateModel(
            name='HistoriqueClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_action', models.CharField(choices=[('CREATION', 'Création'), ('MODIFICATION', 'Modification'), ('STATUS_CHANGE', 'Changement de statut'), ('BLACKLIST', 'Blacklist'), ('DOCUMENT', 'Document ajouté')], max_length=50, verbose_name="Type d'action")),
                ('date_action', models.DateTimeField(auto_now_add=True, verbose_name="Date de l'action")),
                ('description', models.TextField(verbose_name='Description')),
                ('anciennes_valeurs', models.JSONField(blank=True, null=True, verbose_name='Anciennes valeurs')),
                ('nouvelles_valeurs', models.JSONField(blank=True, null=True, verbose_name='Nouvelles valeurs')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='bank.client')),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Historique client',
                'verbose_name_plural': 'Historiques clients',
                'ordering': ['-date_action'],
            },
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['nom'], name='bank_client_nom_f5c45f_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['est_actif'], name='bank_client_est_act_a33112_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['est_blackliste'], name='bank_client_est_bla_a52d85_idx'),
        ),
    ]
