# Generated by Django 6.0.1 on 2026-04-09 23:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut_dossier', models.CharField(choices=[('INCOMPLET', 'Dossier Incomplet'), ('EVALUATION', "En cours d'évaluation"), ('VALIDE', 'Validé / Éligible'), ('BLOQUE', 'Bloqué')], default='INCOMPLET', max_length=15)),
                ('montant_pret_actuel', models.DecimalField(decimal_places=2, default=0, max_digits=30)),
                ('plafond_pret_max', models.DecimalField(decimal_places=2, default=0, max_digits=30)),
                ('date_dernier_pret', models.DateField(blank=True, null=True)),
                ('revenus_mensuels', models.DecimalField(decimal_places=2, default=0, max_digits=30)),
                ('depenses_mensuelles', models.DecimalField(decimal_places=2, default=0, max_digits=30)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('raison_blocage', models.TextField(blank=True, null=True)),
                ('date_blocage', models.DateTimeField(blank=True, editable=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_paiement', models.DateTimeField(default=django.utils.timezone.now)),
                ('montant_paye', models.DecimalField(decimal_places=2, max_digits=30)),
                ('mode_paiement', models.CharField(choices=[('CASH', 'Espèces'), ('MOBILE', 'Mobile paiement')], default='CASH', max_length=50)),
                ('penalite_payee', models.DecimalField(decimal_places=2, default=0, max_digits=30, verbose_name='Pénalité Versée')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Remboursement',
                'verbose_name_plural': 'Remboursements',
            },
        ),
        migrations.CreateModel(
            name='Pret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_pret', models.CharField(max_length=20, unique=True, verbose_name='N° Prêt')),
                ('montant_accorde', models.DecimalField(decimal_places=2, default=0, max_digits=30, verbose_name='Montant')),
                ('taux_interet', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('taux_penalite', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('frequence_paiement', models.CharField(choices=[('JOUR', 'Journalier'), ('SEMAINE', 'Hebdomadaire'), ('MOIS', 'Mensuel')], default='SEMAINE', max_length=10)),
                ('jour_remboursement', models.IntegerField(choices=[(0, 'Lundi'), (1, 'Mardi'), (2, 'Mercredi'), (3, 'Jeudi'), (4, 'Vendredi'), (5, 'Samedi'), (6, 'Dimanche')], default=0)),
                ('duree', models.IntegerField(default=1)),
                ('date_pret', models.DateField(auto_now_add=True)),
                ('is_solde', models.BooleanField(default=False)),
                ('frais_dossier_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
