# Generated by Django 6.0.1 on 2026-04-09 23:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bank', '0001_initial'),
        ('societe', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='agent_responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='societe.employe'),
        ),
        migrations.AddField(
            model_name='client',
            name='created_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients_crees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='client',
            name='tiers',
            field=models.OneToOneField(error_messages={'unique': 'Ce client possède déjà un compte.'}, on_delete=django.db.models.deletion.PROTECT, related_name='profil_client', to='societe.tiers', verbose_name='Info Clients'),
        ),
        migrations.AddField(
            model_name='client',
            name='updated_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients_modifier', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paiement',
            name='agent_responsable',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='societe.employe'),
        ),
        migrations.AddField(
            model_name='paiement',
            name='cree_par',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='paiements_crees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paiement',
            name='modifie_par',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='paiements_modifies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pret',
            name='agent_responsable',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='societe.employe'),
        ),
        migrations.AddField(
            model_name='pret',
            name='avaliste',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='garanties_donnees', to='societe.tiers', verbose_name='Avaliseur / Garant'),
        ),
        migrations.AddField(
            model_name='pret',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prets', to='bank.client'),
        ),
        migrations.AddField(
            model_name='pret',
            name='cree_par',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prets_crees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pret',
            name='modifie_par',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prets_modifies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paiement',
            name='pret',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paiements', to='bank.pret'),
        ),
    ]
