# Generated by Django 6.0.1 on 2026-03-05 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='client',
            name='bank_client_nom_f5c45f_idx',
        ),
        migrations.RemoveIndex(
            model_name='client',
            name='bank_client_est_act_a33112_idx',
        ),
        migrations.RemoveIndex(
            model_name='client',
            name='bank_client_est_bla_a52d85_idx',
        ),
        migrations.RemoveField(
            model_name='historiqueclient',
            name='client',
        ),
        migrations.RemoveField(
            model_name='historiqueclient',
            name='utilisateur',
        ),
        migrations.RemoveField(
            model_name='client',
            name='agent',
        ),
        migrations.RemoveField(
            model_name='client',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='DocumentClient',
        ),
        migrations.DeleteModel(
            name='HistoriqueClient',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
    ]
