# Generated by Django 6.0.1 on 2026-03-05 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bank', '0002_remove_client_bank_client_nom_f5c45f_idx_and_more'),
        ('societe', '0026_alter_employe_created_at_alter_employe_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut_dossier', models.CharField(choices=[('INCOMPLET', 'Dossier Incomplet'), ('EVALUATION', "En cours d'évaluation"), ('VALIDE', 'Validé / Éligible'), ('BLOQUE', 'Bloqué')], default='INCOMPLET', max_length=15)),
                ('raison_blocage', models.TextField(blank=True, null=True, verbose_name='Raison du blocage / Note interne')),
                ('date_blocage', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Date effective du blocage')),
                ('tiers', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='profil_client', to='societe.tiers', verbose_name='Tiers associé')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
        ),
    ]
