# Generated by Django 6.0.1 on 2026-03-05 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0004_client_agent_responsable_client_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='montant_pret_actuel',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Montant prêté'),
        ),
        migrations.AddField(
            model_name='client',
            name='plafond_pret_max',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Maximum autorisé'),
        ),
    ]
