# Generated by Django 6.0.1 on 2026-03-05 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0005_client_montant_pret_actuel_client_plafond_pret_max'),
        ('societe', '0027_alter_tiers_prenoms'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='date_dernier_pret',
            field=models.DateField(blank=True, null=True, verbose_name='Date du dernier prêt'),
        ),
        migrations.AlterField(
            model_name='client',
            name='tiers',
            field=models.OneToOneField(error_messages={'unique': 'Ce client possède déjà un compte .'}, on_delete=django.db.models.deletion.PROTECT, related_name='profil_client', to='societe.tiers', verbose_name='Info Cients'),
        ),
    ]
