# Generated by Django 6.0.1 on 2026-03-06 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0006_client_date_dernier_pret_alter_client_tiers'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='depenses_mensuelles',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Dépenses/Charges (Mensuel)'),
        ),
        migrations.AddField(
            model_name='client',
            name='description_activite',
            field=models.TextField(blank=True, verbose_name="Détails de l'activité"),
        ),
        migrations.AddField(
            model_name='client',
            name='revenus_mensuels',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Entrées/Revenus (Mensuel)'),
        ),
        migrations.AddField(
            model_name='client',
            name='type_activite',
            field=models.CharField(choices=[('COMMERCE', 'Commerce'), ('AGRICULTURE', 'Agriculture'), ('SERVICE', 'Prestation de Service'), ('INDUSTRIE', 'Industrie/Production'), ('SALARIE', 'Salarié'), ('AUTRE', 'Autre')], default='COMMERCE', max_length=20, verbose_name="Type d'activité"),
        ),
    ]
