# Generated by Django 6.0.1 on 2026-03-06 03:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0007_client_depenses_mensuelles_and_more'),
        ('societe', '0027_alter_tiers_prenoms'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='reference_tiers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='references_donnees', to='societe.tiers', verbose_name='Personne de référence'),
        ),
        migrations.AddField(
            model_name='client',
            name='relation_reference',
            field=models.CharField(blank=True, max_length=100, verbose_name='Lien / Relation (ex: Frère, Employeur)'),
        ),
    ]
