# Generated by Django 6.0.1 on 2026-03-06 07:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0008_client_reference_tiers_client_relation_reference'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='created_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients_crees', to=settings.AUTH_USER_MODEL, verbose_name='créé par'),
        ),
        migrations.AlterField(
            model_name='client',
            name='date_blocage',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Date du blocage'),
        ),
        migrations.AlterField(
            model_name='client',
            name='date_update',
            field=models.DateTimeField(auto_now=True, verbose_name='date modifiéé'),
        ),
        migrations.AlterField(
            model_name='client',
            name='relation_reference',
            field=models.CharField(blank=True, max_length=100, verbose_name='Lien / Relation (ex: Frère)'),
        ),
        migrations.AlterField(
            model_name='client',
            name='updated_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients_modifier', to=settings.AUTH_USER_MODEL, verbose_name='Modiféé par'),
        ),
        migrations.CreateModel(
            name='Pret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_pret', models.CharField(max_length=20, unique=True, verbose_name='N° du Prêt')),
                ('montant_accorde', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant')),
                ('taux_interet', models.DecimalField(decimal_places=2, help_text='En %', max_digits=5)),
                ('frequence_paiement', models.CharField(choices=[('JOUR', 'Journalier'), ('SEMAINE', 'Hebdomadaire'), ('MOIS', 'Mensuel')], default='MOIS', max_length=10, verbose_name='Fréquence de paiement')),
                ('duree', models.IntegerField(help_text='Ex: 10 (jours, semaines ou mois)', verbose_name="Nombre d'échéances")),
                ('date_pret', models.DateField(auto_now_add=True)),
                ('is_solde', models.BooleanField(default=False, verbose_name='Prêt Soldé')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prets', to='bank.client')),
            ],
            options={
                'verbose_name': 'Prêt',
                'verbose_name_plural': 'Prêts',
            },
        ),
    ]
