# Generated by Django 6.0.1 on 2026-03-06 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0009_alter_client_created_by_alter_client_date_blocage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pret',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prets', to='bank.client'),
        ),
    ]
