# Generated by Django 6.0.1 on 2026-03-06 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0010_alter_pret_client'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pret',
            options={},
        ),
        migrations.AddField(
            model_name='pret',
            name='jour_remboursement',
            field=models.IntegerField(choices=[(0, 'Lundi'), (1, 'Mardi'), (2, 'Mercredi'), (3, 'Jeudi'), (4, 'Vendredi'), (5, 'Samedi'), (6, 'Dimanche')], default=0, verbose_name='Jour de collecte'),
        ),
        migrations.AlterField(
            model_name='pret',
            name='duree',
            field=models.IntegerField(verbose_name="Nombre d'échéances"),
        ),
        migrations.AlterField(
            model_name='pret',
            name='frequence_paiement',
            field=models.CharField(choices=[('JOUR', 'Journalier'), ('SEMAINE', 'Hebdomadaire'), ('MOIS', 'Mensuel')], default='SEMAINE', max_length=10),
        ),
    ]
