# Generated by Django 6.0.1 on 2026-03-06 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0011_alter_pret_options_pret_jour_remboursement_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pret',
            options={'verbose_name': 'Prêt', 'verbose_name_plural': 'Prêts'},
        ),
        migrations.AddField(
            model_name='pret',
            name='taux_penalite',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Appliquée par fréquence de retard', max_digits=5, verbose_name='Pénalité (%)'),
        ),
        migrations.AlterField(
            model_name='pret',
            name='montant_accorde',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant Prêté'),
        ),
        migrations.AlterField(
            model_name='pret',
            name='taux_interet',
            field=models.DecimalField(decimal_places=2, help_text='Intérêt normal en %', max_digits=5),
        ),
    ]
