# Generated by Django 6.0.1 on 2026-03-06 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0012_alter_pret_options_pret_taux_penalite_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pret',
            options={},
        ),
        migrations.AlterField(
            model_name='pret',
            name='jour_remboursement',
            field=models.IntegerField(choices=[(0, 'Lundi'), (1, 'Mardi'), (2, 'Mercredi'), (3, 'Jeudi'), (4, 'Vendredi'), (5, 'Samedi'), (6, 'Dimanche')], default=0),
        ),
        migrations.AlterField(
            model_name='pret',
            name='montant_accorde',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant'),
        ),
        migrations.AlterField(
            model_name='pret',
            name='taux_interet',
            field=models.DecimalField(decimal_places=2, help_text='En %', max_digits=5),
        ),
        migrations.AlterField(
            model_name='pret',
            name='taux_penalite',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Pénalité (%)'),
        ),
    ]
