# Generated by Django 6.0.1 on 2026-03-06 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0013_alter_pret_options_alter_pret_jour_remboursement_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pret',
            options={'verbose_name': 'Prêt', 'verbose_name_plural': 'Prêts'},
        ),
        migrations.AlterField(
            model_name='pret',
            name='duree',
            field=models.IntegerField(blank=True, null=True, verbose_name="Nombre d'échéances"),
        ),
        migrations.AlterField(
            model_name='pret',
            name='jour_remboursement',
            field=models.IntegerField(choices=[(0, 'Lundi'), (1, 'Mardi'), (2, 'Mercredi'), (3, 'Jeudi'), (4, 'Vendredi'), (5, 'Samedi'), (6, 'Dimanche')], default=0, verbose_name='Jour de collecte'),
        ),
        migrations.AlterField(
            model_name='pret',
            name='montant_accorde',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Montant'),
        ),
        migrations.AlterField(
            model_name='pret',
            name='taux_interet',
            field=models.DecimalField(decimal_places=2, default=0, help_text='En %', max_digits=5),
        ),
    ]
