# Generated by Django 6.0.1 on 2026-03-06 09:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0014_alter_pret_options_alter_pret_duree_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_paiement', models.DateField(default=django.utils.timezone.now)),
                ('montant_paye', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Somme Versée')),
                ('commentaire', models.CharField(blank=True, max_length=255, null=True)),
                ('pret', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='bank.pret')),
            ],
            options={
                'verbose_name': 'Enregistrement de Paiement',
                'verbose_name_plural': 'Saisie des Paiements',
            },
        ),
    ]
