# Generated by Django 6.0.1 on 2026-03-06 19:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0015_paiement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paiement',
            options={'verbose_name': 'Remboursement', 'verbose_name_plural': 'Journal des Remboursements'},
        ),
        migrations.AddField(
            model_name='paiement',
            name='mode_paiement',
            field=models.CharField(choices=[('CASH', 'Espèces'), ('MOBILE', 'Mobile Money')], default='CASH', max_length=50),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='date_paiement',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date/Heure du versement'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='pret',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='bank.pret', verbose_name='N° de Prêt'),
        ),
    ]
