# Generated by Django 6.0.1 on 2026-03-06 21:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0016_alter_paiement_options_paiement_mode_paiement_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paiement',
            options={},
        ),
        migrations.AlterModelOptions(
            name='pret',
            options={},
        ),
        migrations.RemoveField(
            model_name='paiement',
            name='commentaire',
        ),
        migrations.AlterField(
            model_name='paiement',
            name='date_paiement',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='montant_paye',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='pret',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='bank.pret'),
        ),
        migrations.AlterField(
            model_name='pret',
            name='duree',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pret',
            name='is_solde',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pret',
            name='jour_remboursement',
            field=models.IntegerField(choices=[(0, 'Lundi'), (1, 'Mardi'), (2, 'Mercredi'), (3, 'Jeudi'), (4, 'Vendredi'), (5, 'Samedi'), (6, 'Dimanche')], default=0),
        ),
        migrations.AlterField(
            model_name='pret',
            name='montant_accorde',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='pret',
            name='taux_interet',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='pret',
            name='taux_penalite',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
