# Generated by Django 6.0.1 on 2026-03-08 04:55

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0017_alter_paiement_options_alter_pret_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='cree_par',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='paiements_crees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paiement',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 3, 8, 4, 54, 51, 450571, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paiement',
            name='date_modification',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='paiement',
            name='modifie_par',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='paiements_modifies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pret',
            name='cree_par',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prets_crees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pret',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 3, 8, 4, 55, 5, 143019, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pret',
            name='date_modification',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='pret',
            name='modifie_par',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prets_modifies', to=settings.AUTH_USER_MODEL),
        ),
    ]
