# Generated by Django 6.0.1 on 2026-03-08 06:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0018_paiement_cree_par_paiement_date_creation_and_more'),
        ('societe', '0027_alter_tiers_prenoms'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={},
        ),
        migrations.RemoveField(
            model_name='client',
            name='description_activite',
        ),
        migrations.RemoveField(
            model_name='client',
            name='reference_tiers',
        ),
        migrations.RemoveField(
            model_name='client',
            name='relation_reference',
        ),
        migrations.RemoveField(
            model_name='client',
            name='type_activite',
        ),
        migrations.AlterField(
            model_name='client',
            name='agent_responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='societe.employe'),
        ),
        migrations.AlterField(
            model_name='client',
            name='created_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients_crees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='client',
            name='date_blocage',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='date_dernier_pret',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='date_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='depenses_mensuelles',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='client',
            name='montant_pret_actuel',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='client',
            name='plafond_pret_max',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='client',
            name='raison_blocage',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='revenus_mensuels',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='client',
            name='tiers',
            field=models.OneToOneField(error_messages={'unique': 'Ce client possède déjà un compte.'}, on_delete=django.db.models.deletion.PROTECT, related_name='profil_client', to='societe.tiers', verbose_name='Info Clients'),
        ),
        migrations.AlterField(
            model_name='client',
            name='updated_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients_modifier', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='cree_par',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='paiements_crees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='modifie_par',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='paiements_modifies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pret',
            name='code_pret',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='pret',
            name='cree_par',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prets_crees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pret',
            name='duree',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='pret',
            name='modifie_par',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prets_modifies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pret',
            name='montant_accorde',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
