# Generated by Django 6.0.1 on 2026-03-08 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0019_alter_client_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiement',
            name='pret',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paiements', to='bank.pret'),
        ),
    ]
