# Generated by Django 6.0.1 on 2026-03-08 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0020_alter_paiement_pret'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='penalite_payee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Pénalité Versée'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='mode_paiement',
            field=models.CharField(choices=[('CASH', 'Espèces'), ('MOBILE', 'Mobile paiement')], default='CASH', max_length=50),
        ),
    ]
