# Generated by Django 6.0.1 on 2026-03-08 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0021_paiement_penalite_payee_alter_paiement_mode_paiement'),
        ('societe', '0027_alter_tiers_prenoms'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='agent_responsable',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='societe.employe'),
        ),
        migrations.AddField(
            model_name='pret',
            name='agent_responsable',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='societe.employe'),
        ),
    ]
