# Generated by Django 6.0.1 on 2026-03-14 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0022_paiement_agent_responsable_pret_agent_responsable'),
        ('societe', '0029_paiementemploye'),
    ]

    operations = [
        migrations.AddField(
            model_name='pret',
            name='avaliste',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='garanties_donnees', to='societe.tiers', verbose_name='Avaliseur / Garant'),
        ),
    ]
