# Generated by Django 6.0.1 on 2026-03-15 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0024_pret_frais_dossier_pct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pret',
            name='frais_dossier_pct',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
