# Generated by Django 6.0.1 on 2026-03-15 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0025_alter_pret_frais_dossier_pct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pret',
            name='code_pret',
            field=models.CharField(editable=False, max_length=20, unique=True, verbose_name='N° Prêt'),
        ),
        migrations.AlterField(
            model_name='pret',
            name='montant_accorde',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Montant'),
        ),
    ]
