# Generated by Django 6.0.1 on 2026-03-15 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0026_alter_pret_code_pret_alter_pret_montant_accorde'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pret',
            name='code_pret',
            field=models.CharField(max_length=20, unique=True, verbose_name='N° Prêt'),
        ),
    ]
