# Generated by Django 6.0.1 on 2026-02-16 23:49

import django.db.models.deletion
import django_countries.fields
import smart_selects.db_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', django_countries.fields.CountryField(max_length=2, null=True)),
            ],
            options={
                'verbose_name': 'Pays',
                'verbose_name_plural': 'Pays',
            },
        ),
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('pays', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parametres.pays')),
            ],
            options={
                'verbose_name': 'Département',
                'verbose_name_plural': 'Départements',
            },
        ),
        migrations.CreateModel(
            name='Ville',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametres.departement')),
            ],
            options={
                'verbose_name': 'Ville',
                'verbose_name_plural': 'Villes',
            },
        ),
        migrations.CreateModel(
            name='Adresse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parametres.departement')),
                ('ville', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='departement', chained_model_field='departement', on_delete=django.db.models.deletion.CASCADE, to='parametres.ville')),
            ],
            options={
                'verbose_name': 'Adresse',
                'verbose_name_plural': 'Adresses',
            },
        ),
        migrations.AddConstraint(
            model_name='departement',
            constraint=models.UniqueConstraint(fields=('nom', 'pays'), name='unique_ville_pays'),
        ),
        migrations.AddConstraint(
            model_name='ville',
            constraint=models.UniqueConstraint(fields=('departement', 'nom'), name='unique_ville_departement'),
        ),
    ]
