# Generated by Django 6.0.1 on 2026-04-09 20:40

import django.db.models.deletion
import django_countries.fields
import smart_selects.db_fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('HTG', 'Gourde Haïtienne'), ('USD', 'Dollar Américain'), ('EUR', 'Euro'), ('$HT', 'Dollar Haïtien'), ('CAD', 'Dollar Canadien'), ('DOP', 'Peso Dominicain')], max_length=3, unique=True, verbose_name='Devise')),
                ('code', models.CharField(editable=False, max_length=3, unique=True, verbose_name='Code ISO')),
                ('symbol', models.CharField(editable=False, max_length=10, verbose_name='Symbole')),
                ('exchange_rate', models.DecimalField(decimal_places=4, default=1.0, max_digits=15, verbose_name='Taux')),
                ('is_default', models.BooleanField(default=False, verbose_name='Par défaut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créée le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifiée  le')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='crée par')),
            ],
            options={
                'verbose_name': 'Monnaie',
                'verbose_name_plural': 'Monnaies',
            },
        ),
        migrations.CreateModel(
            name='Pays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', django_countries.fields.CountryField(max_length=2, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='créer par')),
            ],
            options={
                'verbose_name': 'Pays',
                'verbose_name_plural': 'Pays',
            },
        ),
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='créer par')),
                ('pays', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parametres.pays')),
            ],
            options={
                'verbose_name': 'Département',
                'verbose_name_plural': 'Départements',
            },
        ),
        migrations.CreateModel(
            name='Ville',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='créer par')),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametres.departement')),
            ],
            options={
                'verbose_name': 'Ville',
                'verbose_name_plural': 'Villes',
            },
        ),
        migrations.CreateModel(
            name='Adresse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='créer par')),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parametres.departement')),
                ('ville', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='departement', chained_model_field='departement', on_delete=django.db.models.deletion.CASCADE, to='parametres.ville')),
            ],
            options={
                'verbose_name': 'Adresse',
                'verbose_name_plural': 'Adresses',
            },
        ),
        migrations.AddConstraint(
            model_name='departement',
            constraint=models.UniqueConstraint(fields=('nom', 'pays'), name='unique_ville_pays'),
        ),
        migrations.AddConstraint(
            model_name='ville',
            constraint=models.UniqueConstraint(fields=('departement', 'nom'), name='unique_ville_departement'),
        ),
    ]
