# Generated by Django 6.0.1 on 2026-04-10 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ville',
            name='nom',
            field=models.CharField(max_length=255),
        ),
    ]
