# Generated by Django 6.0.1 on 2026-02-19 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('HTG', 'Gourde Haïtienne (HTG)'), ('USD', 'Dollar Américain (USD)'), ('EUR', 'Euro (EUR)'), ('CAD', 'Dollar Canadien (CAD)'), ('DOP', 'Peso Dominicain (DOP)')], max_length=3, unique=True, verbose_name='Devise')),
                ('code', models.CharField(editable=False, max_length=3, unique=True, verbose_name='Code ISO')),
                ('symbol', models.CharField(editable=False, max_length=10, verbose_name='Symbole')),
                ('exchange_rate', models.DecimalField(decimal_places=4, default=1.0, max_digits=15, verbose_name='Taux')),
                ('is_default', models.BooleanField(default=False, verbose_name='Par défaut')),
            ],
        ),
    ]
