# Generated by Django 6.0.1 on 2026-02-19 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0002_currency'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currency',
            options={'verbose_name': 'Monnaie', 'verbose_name_plural': 'Monnaies'},
        ),
    ]
