# Generated by Django 6.0.1 on 2026-02-19 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0003_alter_currency_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='name',
            field=models.CharField(choices=[('HTG', 'Gourde Haïtienne'), ('USD', 'Dollar Américain'), ('EUR', 'Euro'), ('$HT', 'Dollar Haïtien'), ('CAD', 'Dollar Canadien'), ('DOP', 'Peso Dominicain')], max_length=3, unique=True, verbose_name='Devise'),
        ),
    ]
