# Generated by Django 6.0.1 on 2026-02-16 23:49

import django.core.validators
import django.db.models.deletion
import phonenumber_field.modelfields
import smart_selects.db_fields
import societe.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parametres', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(3)], verbose_name="Nom de l'entreprise")),
                ('sigle', models.CharField(validators=[django.core.validators.MinLengthValidator(3)], verbose_name="Sigle de l'entreprise")),
                ('logo', models.ImageField(upload_to='company/logos/', verbose_name='Logo Officiel')),
                ('slogan', models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Slogan')),
                ('email_contact', models.EmailField(max_length=254, verbose_name='Email de contact')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Site Web')),
                ('currency', models.CharField(default='$ HT', help_text='Exemple: $ HT, HTG, ou USD', max_length=10, verbose_name='Symbole Monétaire')),
                ('default_interest_rate', models.DecimalField(decimal_places=2, default=5.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name="Taux d'intérêt Pret (%)")),
                ('interet_maison_daffaire', models.DecimalField(decimal_places=2, default=5.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name="Taux d'intérêt Maison d'affaire(%)")),
                ('late_fee_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Frais de Retard')),
                ('tax_id', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='NIF / Matricule Fiscale')),
                ('legal_status', models.CharField(choices=[('IND', 'Entreprise Individuelle'), ('SARL', 'S.A.R.L (Soc. à Responsabilité Limitée)'), ('SA', 'S.A (Société Anonyme)'), ('ONG', 'Organisation Non Gouvernementale')], default='SARL', max_length=10)),
                ('capital', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Capital Social')),
                ('date_creation', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='créer par')),
            ],
            options={
                'verbose_name': "Information de l'Entreprise",
                'verbose_name_plural': "Informations de l'Entreprise",
            },
        ),
        migrations.CreateModel(
            name='CompanyAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_address', models.CharField(max_length=500, verbose_name='Adresse résidentielle')),
                ('is_principal', models.BooleanField(default=False, verbose_name='Adresse principale')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='societe.company')),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parametres.departement')),
                ('ville', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='departement', chained_model_field='departement', on_delete=django.db.models.deletion.CASCADE, to='parametres.ville')),
            ],
            options={
                'verbose_name': 'Adresse',
                'verbose_name_plural': 'Adresses',
            },
        ),
        migrations.CreateModel(
            name='CompanyBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100, verbose_name='Nom de la Banque')),
                ('account_holder', models.CharField(help_text='Nom exact figurant sur le relevé bancaire', max_length=150, verbose_name='Titulaire du Compte')),
                ('account_number', models.CharField(max_length=50, verbose_name='Numéro de Compte')),
                ('account_type', models.CharField(max_length=50, verbose_name='Type de compte')),
                ('currency', models.CharField(choices=[('HTG', 'Gourdes (HTG)'), ('USD', 'Dollars (USD)')], default='HTG', max_length=3, verbose_name='Monnaie')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banks', to='societe.company')),
            ],
            options={
                'verbose_name': 'Information Bancaire',
                'verbose_name_plural': 'Informations Bancaires',
            },
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Ex: Bureau, WhatsApp, Urgence', max_length=50, verbose_name='Étiquette')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(help_text='Entrez le numéro au format international (ex: +509 XXXX XXXX pour Haïti ).', max_length=128, region=None, verbose_name='Téléphone')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='societe.company')),
            ],
        ),
        migrations.CreateModel(
            name='Tiers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Code')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenoms', models.CharField(max_length=100, verbose_name='Prénoms')),
                ('date_naissance', models.DateField(validators=[societe.models.validate_age_minimum], verbose_name='Date de naissance')),
                ('genre', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin'), ('A', 'Autre')], max_length=1, verbose_name='Genre')),
                ('statut_matrimonial', models.CharField(choices=[('C', 'Célibataire'), ('M', 'Marié(e)'), ('D', 'Divorcé(e)'), ('V', 'Veuf/Veuve'), ('S', 'Séparé(e)')], max_length=1, verbose_name='Statut matrimonial')),
                ('telephone', phonenumber_field.modelfields.PhoneNumberField(help_text='Entrez le numéro au format international (ex: +509 XXXX XXXX pour Haïti ).', max_length=128, region=None, verbose_name='Téléphone')),
                ('telephone_aditionnel', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Entrez le numéro au format international (ex: +509 XXXX XXXX pour Haïti ).', max_length=128, region=None, verbose_name='Téléphone additionnel')),
                ('email', models.EmailField(blank=True, max_length=254, unique=True, verbose_name='Adresse email')),
                ('adresse', models.CharField(max_length=200, verbose_name='Adresse résidentielle')),
                ('adresse_additionnelle', models.CharField(blank=True, max_length=200, verbose_name='Adresse Aditionnelle')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type_piece_identite', models.CharField(choices=[('NINU', "Carte Nationale d'Identité"), ('PASSEPORT', 'Passeport'), ('PERMIS', 'Permis de conduire'), ('NIF', 'Matricule fiscal')], max_length=20, verbose_name="Type de pièce d'identité")),
                ('numero_piece', models.CharField(max_length=50, unique=True, verbose_name='Numéro de pièce')),
                ('niveau_etude', models.CharField(choices=[('PRIMAIRE', 'Primaire'), ('SECONDAIRE', 'Secondaire'), ('BACC', 'Baccalauréat'), ('DIPLOME', 'Diplome'), ('LICENCE', 'Licence'), ('MASTER', 'Master'), ('DOCTORAT', 'Doctorat'), ('AUTRE', 'Autre')], max_length=20, verbose_name="Niveau d'étude")),
                ('nombre_enfants', models.PositiveIntegerField(default=0, verbose_name="Nombre d'enfants")),
                ('photo', models.ImageField(blank=True, null=True, upload_to='clients/photos/', verbose_name="Photo d'identite")),
                ('piece_identite_recto', models.ImageField(blank=True, null=True, upload_to='clients/pieces_identite/', verbose_name="Recto Pièce d'identité ")),
                ('piece_identite_verso', models.ImageField(blank=True, null=True, upload_to='clients/pieces_identite/', verbose_name="Pièce d'identité (verso)")),
                ('signature', models.ImageField(blank=True, null=True, upload_to='clients/signatures/', verbose_name='Signature')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='créer par')),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parametres.departement')),
                ('ville', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='departement', chained_model_field='departement', on_delete=django.db.models.deletion.CASCADE, to='parametres.ville')),
            ],
            options={
                'verbose_name': 'Tier',
                'verbose_name_plural': 'Tiers',
                'constraints': [models.UniqueConstraint(fields=('nom', 'prenoms', 'date_naissance'), name='unique_client_identity')],
            },
        ),
    ]
