# Generated by Django 6.0.1 on 2026-04-09 23:25

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields
import smart_selects.db_fields
import societe.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('parametres', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(3)], verbose_name="Nom de l'entreprise")),
                ('sigle', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(3)], verbose_name="Sigle de l'entreprise")),
                ('logo', models.ImageField(upload_to='company/logos/', verbose_name='Logo Officiel')),
                ('slogan', models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Slogan')),
                ('email_contact', models.EmailField(max_length=254, verbose_name='Email de contact')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Site Web')),
                ('default_interest_rate', models.DecimalField(decimal_places=2, default=5.0, max_digits=20, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name="Taux d'intérêt Pret (%)")),
                ('interet_maison_daffaire', models.DecimalField(decimal_places=2, default=5.0, max_digits=20, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name="Taux d'intérêt Maison d'affaire(%)")),
                ('late_fee_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='Frais de Retard')),
                ('tax_id', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='NIF / Matricule Fiscale')),
                ('legal_status', models.CharField(choices=[('IND', 'Entreprise Individuelle'), ('SARL', 'S.A.R.L (Soc. à Responsabilité Limitée)'), ('SA', 'S.A (Société Anonyme)'), ('ONG', 'Organisation Non Gouvernementale')], default='SARL', max_length=10)),
                ('capital', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='Capital Social')),
                ('frais_dossier_pct', models.DecimalField(decimal_places=2, default=0.0, help_text='Pourcentage des frais de dossier appliqué à ce client', max_digits=20, verbose_name='Frais de dossier (%)')),
                ('date_creation', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='créer par')),
                ('currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='parametres.currency')),
            ],
            options={
                'verbose_name': "Information de l'Entreprise",
                'verbose_name_plural': "Informations de l'Entreprise",
            },
        ),
        migrations.CreateModel(
            name='CompanyAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_address', models.CharField(max_length=500, verbose_name='Adresse résidentielle')),
                ('is_principal', models.BooleanField(default=False, verbose_name='Adresse principale')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='societe.company')),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parametres.departement')),
                ('ville', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='departement', chained_model_field='departement', on_delete=django.db.models.deletion.CASCADE, to='parametres.ville')),
            ],
            options={
                'verbose_name': 'Adresse',
                'verbose_name_plural': 'Adresses',
            },
        ),
        migrations.CreateModel(
            name='CompanyBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100, verbose_name='Nom de la Banque')),
                ('account_holder', models.CharField(help_text='Nom exact figurant sur le relevé bancaire', max_length=150, verbose_name='Titulaire du Compte')),
                ('account_number', models.CharField(max_length=50, verbose_name='Numéro de Compte')),
                ('account_type', models.CharField(max_length=50, verbose_name='Type de compte')),
                ('currency', models.CharField(choices=[('HTG', 'Gourdes (HTG)'), ('USD', 'Dollars (USD)')], default='HTG', max_length=3, verbose_name='Monnaie')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banks', to='societe.company')),
            ],
            options={
                'verbose_name': 'Information Bancaire',
                'verbose_name_plural': 'Informations Bancaires',
            },
        ),
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('est_approbateur', models.BooleanField(default=False, verbose_name="Droit d'approbation")),
                ('date_embauche', models.DateField(verbose_name="Date d'embauche")),
                ('doit_changer_mot_de_passe', models.BooleanField(default=True, verbose_name='Doit changer de MDP')),
                ('salaire_base', models.DecimalField(decimal_places=2, default=0.0, help_text='Le salaire doit être supérieur à 0.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créer le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifiier le')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employes_crees', to=settings.AUTH_USER_MODEL, verbose_name='créer par')),
                ('poste', models.ManyToManyField(help_text='Maintenez CTRL pour en sélectionner plusieurs', to='auth.group', verbose_name="Postes / Groupes d'accès")),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='profil_employe', to=settings.AUTH_USER_MODEL, verbose_name='Compte Utilisateur')),
            ],
            options={
                'verbose_name': 'Employé',
                'verbose_name_plural': 'Employés',
            },
        ),
        migrations.CreateModel(
            name='Depense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Motif de la dépense')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date_depense', models.DateField(default=django.utils.timezone.now, verbose_name='Date effective')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Détails supplémentaires')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('enregistre_par', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='depenses_enregistrees', to=settings.AUTH_USER_MODEL)),
                ('employe_responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='depenses_gerees', to='societe.employe', verbose_name='Employé responsable')),
            ],
            options={
                'verbose_name': 'Dépense',
                'verbose_name_plural': 'Dépenses',
                'ordering': ['-date_depense'],
            },
        ),
        migrations.CreateModel(
            name='PaiementEmploye',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant payé')),
                ('date_paiement', models.DateField(default=django.utils.timezone.now, verbose_name='Date du paiement')),
                ('motif', models.CharField(help_text='Ex: Salaire Mars 2026, Prime, etc.', max_length=255, verbose_name='Motif')),
                ('notes', models.TextField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mes_paiements', to='societe.employe', verbose_name='Employé bénéficiaire')),
                ('enregistre_par', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Paiement Employé',
                'verbose_name_plural': 'Paiements Employés',
                'ordering': ['-date_paiement'],
            },
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Ex: Bureau, WhatsApp, Urgence', max_length=50, verbose_name='Étiquette')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(help_text='Entrez le numéro au format international (ex: +509 XXXX XXXX pour Haïti ).', max_length=128, region=None, verbose_name='Téléphone')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='societe.company')),
            ],
        ),
        migrations.CreateModel(
            name='Tiers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Code')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenoms', models.CharField(max_length=100, verbose_name='Prénom')),
                ('date_naissance', models.DateField(validators=[societe.models.validate_age_minimum], verbose_name='Date de naissance')),
                ('genre', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin'), ('A', 'Autre')], max_length=1, verbose_name='Genre')),
                ('statut_matrimonial', models.CharField(choices=[('C', 'Célibataire'), ('M', 'Marié(e)'), ('D', 'Divorcé(e)'), ('V', 'Veuf/Veuve'), ('S', 'Séparé(e)')], max_length=1, verbose_name='Statut matrimonial')),
                ('religion', models.CharField(choices=[('BAPTISTE', 'Baptiste'), ('ADVENTISTE', 'Adventiste'), ('CATHOLIQUE', 'Catholique'), ('JEHOVAH', 'Témoin de Jéhovah'), ('MORMON', 'Mormon'), ('MUSULMAN', 'Musulman'), ('PENTECOTISTE', 'Pentecôtiste'), ('PROTESTANT', 'Protestant'), ('VODOUISANT', 'Vodouisant'), ('AUTRE', 'Autre'), ('AUCUNE', 'Aucune / Athée')], max_length=20, null=True, verbose_name='Religion')),
                ('email', models.EmailField(blank=True, max_length=254, unique=True, verbose_name='Adresse email')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('niveau_etude', models.CharField(choices=[('PRIMAIRE', 'Primaire'), ('SECONDAIRE', 'Secondaire'), ('BACC', 'Baccalauréat'), ('DIPLOME', 'Diplome'), ('LICENCE', 'Licence'), ('MASTER', 'Master'), ('DOCTORAT', 'Doctorat'), ('AUTRE', 'Autre')], max_length=20, verbose_name="Niveau d'étude")),
                ('nombre_enfants', models.PositiveIntegerField(default=0, verbose_name="Nombre d'enfants")),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='créer par')),
            ],
            options={
                'verbose_name': 'Tier',
                'verbose_name_plural': 'Tiers',
            },
        ),
        migrations.CreateModel(
            name='IdentityDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_piece', models.CharField(choices=[('NINU', "Numéro d'Identification Nationale Unique"), ('PASSEPORT', 'Passeport'), ('PERMIS', 'Permis de conduire'), ('AUTRES', 'AUTRES')], max_length=20, verbose_name='Type de pièce')),
                ('numero_document', models.CharField(help_text='Ce numéro doit être unique (NIF, CIN ou Passeport)', max_length=50, unique=True, verbose_name='Numéro de la pièce')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='clients/photos/', verbose_name="Photo d'identité (Profil)")),
                ('piece_identite_recto', models.ImageField(blank=True, null=True, upload_to='clients/pieces_identite/', verbose_name='Recto / Page principale')),
                ('piece_identite_verso', models.ImageField(blank=True, null=True, upload_to='clients/pieces_identite/', verbose_name='Verso (laisser vide pour Passeport)')),
                ('signature', models.ImageField(blank=True, null=True, upload_to='clients/signatures/', verbose_name='Signature')),
                ('tiers', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='identity_docs', to='societe.tiers')),
            ],
            options={
                'verbose_name': "Document d'identité",
                'verbose_name_plural': "Documents d'identité",
            },
        ),
        migrations.AddField(
            model_name='employe',
            name='tiers',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='profil_employe', to='societe.tiers'),
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_contact', models.CharField(choices=[('Telephone Mobile', 'Telephone Mobile'), ('Telephone domicile', 'Telephone domicile'), ('email', 'Adresse electronique'), ('fax', 'fax'), ('siteweb', 'Site Web'), ('whatsapp', 'Whatsapp'), ('facebook', 'Facebook'), ('Autre', 'Autre')], max_length=50)),
                ('valeur', models.CharField(max_length=255)),
                ('est_principal', models.BooleanField(default=False, verbose_name='Principal')),
                ('tiers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moyens_contact', to='societe.tiers')),
            ],
            options={
                'verbose_name': 'Moyen de contact',
                'verbose_name_plural': 'Moyens de contact',
            },
        ),
        migrations.CreateModel(
            name='TiersAdresse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_adresse', models.CharField(choices=[('Bureau', 'Bureau'), ('Domicile', 'Domicile'), ('Business', 'Business'), ('Livraison', 'Adresse de livraison'), ('Facturation', 'Adresse de facturation')], max_length=50)),
                ('rue', models.CharField(max_length=255)),
                ('est_principale', models.BooleanField(default=False, verbose_name='Principale')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='créer par')),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parametres.departement')),
                ('tiers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adresses', to='societe.tiers')),
                ('ville', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='departement', chained_model_field='departement', on_delete=django.db.models.deletion.CASCADE, to='parametres.ville')),
            ],
            options={
                'verbose_name': 'Adresse',
            },
        ),
        migrations.AddConstraint(
            model_name='tiers',
            constraint=models.UniqueConstraint(fields=('nom', 'prenoms', 'date_naissance'), name='unique_client_identity'),
        ),
        migrations.AddConstraint(
            model_name='contact',
            constraint=models.UniqueConstraint(fields=('tiers', 'type_contact', 'valeur'), name='unique_contact_par_tiers'),
        ),
        migrations.AddConstraint(
            model_name='tiersadresse',
            constraint=models.UniqueConstraint(fields=('tiers', 'type_adresse', 'rue', 'ville', 'departement'), name='unique_adresse_tiers'),
        ),
    ]
