# Generated by Django 6.0.1 on 2026-02-19 03:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('societe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiers',
            name='type_piece_identite',
            field=models.CharField(choices=[('NINU', "Carte  d'Identité Nationale"), ('PASSEPORT', 'Passeport'), ('PERMIS', 'Permis de conduire'), ('NIF', 'Matricule fiscal')], max_length=20, verbose_name="Type de pièce d'identité"),
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_contact', models.CharField(choices=[('Telephone Mobile', 'Telephone Mobile'), ('Telephone domicile', 'Telephone domicile'), ('email', 'Adresse electronique'), ('fax', 'fax'), ('siteweb', 'Site Web'), ('whatsapp', 'Whatsapp'), ('facebook', 'Facebook'), ('Autre', 'Autre')], max_length=50)),
                ('valeur', models.CharField(max_length=255)),
                ('tiers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='societe.tiers')),
            ],
        ),
    ]
