# Generated by Django 6.0.1 on 2026-02-19 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('societe', '0002_alter_tiers_type_piece_identite_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='est_principal',
            field=models.BooleanField(default=False, verbose_name='Principal'),
        ),
    ]
