# Generated by Django 6.0.1 on 2026-02-19 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('societe', '0003_contact_est_principal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Moyen de contact', 'verbose_name_plural': 'Moyens de contact'},
        ),
        migrations.RemoveField(
            model_name='tiers',
            name='telephone',
        ),
        migrations.RemoveField(
            model_name='tiers',
            name='telephone_aditionnel',
        ),
        migrations.AlterField(
            model_name='contact',
            name='tiers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moyens_contact', to='societe.tiers'),
        ),
        migrations.AddConstraint(
            model_name='contact',
            constraint=models.UniqueConstraint(fields=('tiers', 'type_contact', 'valeur'), name='unique_contact_par_tiers'),
        ),
    ]
