# Generated by Django 6.0.1 on 2026-02-19 07:20

import django.db.models.deletion
import smart_selects.db_fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0001_initial'),
        ('societe', '0004_alter_contact_options_remove_tiers_telephone_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TiersAdresse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_adresse', models.CharField(choices=[('Bureau', 'Bureau'), ('Domicile', 'Domicile'), ('Livraison', 'Adresse de livraison'), ('Facturation', 'Adresse de facturation')], max_length=50)),
                ('rue', models.CharField(max_length=255)),
                ('est_principale', models.BooleanField(default=False, verbose_name='Principale')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='créer par')),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parametres.departement')),
                ('tiers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adresses', to='societe.tiers')),
                ('ville', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='departement', chained_model_field='departement', on_delete=django.db.models.deletion.CASCADE, to='parametres.ville')),
            ],
            options={
                'verbose_name': 'Adresse',
                'constraints': [models.UniqueConstraint(fields=('tiers', 'type_adresse', 'rue', 'ville', 'departement'), name='unique_adresse_tiers')],
            },
        ),
    ]
