# Generated by Django 6.0.1 on 2026-02-19 08:51

import django.core.validators
import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('societe', '0005_tiersadresse'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyaddress',
            options={'verbose_name': 'Adresse Entreprise', 'verbose_name_plural': 'Adresses Entreprise'},
        ),
        migrations.AlterModelOptions(
            name='companybank',
            options={},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={},
        ),
        migrations.AlterModelOptions(
            name='tiersadresse',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='contact',
            name='unique_contact_par_tiers',
        ),
        migrations.RemoveField(
            model_name='tiersadresse',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='tiersadresse',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='tiersadresse',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='company',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='company',
            name='sigle',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3)], verbose_name="Sigle de l'entreprise"),
        ),
        migrations.AlterField(
            model_name='companybank',
            name='account_holder',
            field=models.CharField(max_length=150, verbose_name='Titulaire du Compte'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='type_contact',
            field=models.CharField(choices=[('Telephone Mobile', 'Telephone Mobile'), ('Telephone domicile', 'Telephone domicile'), ('email', 'Email'), ('fax', 'Fax'), ('siteweb', 'Site Web'), ('whatsapp', 'Whatsapp'), ('facebook', 'Facebook'), ('Autre', 'Autre')], max_length=50),
        ),
        migrations.AlterField(
            model_name='phone',
            name='label',
            field=models.CharField(help_text='Ex: Bureau, WhatsApp', max_length=50, verbose_name='Étiquette'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Téléphone'),
        ),
        migrations.AlterField(
            model_name='tiers',
            name='adresse',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='tiers',
            name='adresse_additionnelle',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='tiers',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tiers',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='tiers',
            name='genre',
            field=models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin'), ('A', 'Autre')], max_length=1),
        ),
        migrations.AlterField(
            model_name='tiers',
            name='niveau_etude',
            field=models.CharField(choices=[('PRIMAIRE', 'P'), ('SECONDAIRE', 'S'), ('BACC', 'B'), ('DIPLOME', 'D'), ('LICENCE', 'L'), ('MASTER', 'M'), ('DOCTORAT', 'Doc')], max_length=20),
        ),
        migrations.AlterField(
            model_name='tiers',
            name='nombre_enfants',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tiers',
            name='numero_piece',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='tiers',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='clients/photos/'),
        ),
        migrations.AlterField(
            model_name='tiers',
            name='piece_identite_recto',
            field=models.ImageField(blank=True, null=True, upload_to='clients/pieces_identite/'),
        ),
        migrations.AlterField(
            model_name='tiers',
            name='piece_identite_verso',
            field=models.ImageField(blank=True, null=True, upload_to='clients/pieces_identite/'),
        ),
        migrations.AlterField(
            model_name='tiers',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='clients/signatures/'),
        ),
        migrations.AlterField(
            model_name='tiers',
            name='statut_matrimonial',
            field=models.CharField(choices=[('C', 'Célibataire'), ('M', 'Marié(e)'), ('D', 'Divorcé(e)'), ('V', 'Veuf/Veuve'), ('S', 'Séparé(e)')], max_length=1),
        ),
        migrations.AlterField(
            model_name='tiers',
            name='type_piece_identite',
            field=models.CharField(choices=[('NINU', "Carte d'Identité"), ('PASSEPORT', 'Passeport'), ('PERMIS', 'Permis'), ('NIF', 'NIF')], max_length=20),
        ),
        migrations.AlterField(
            model_name='tiersadresse',
            name='type_adresse',
            field=models.CharField(choices=[('Bureau', 'Bureau'), ('Domicile', 'Domicile'), ('Business', 'Business'), ('Livraison', 'Livraison'), ('Facturation', 'Facturation')], max_length=50),
        ),
    ]
