# Generated by Django 6.0.1 on 2026-02-19 09:02

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('societe', '0006_alter_companyaddress_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyaddress',
            options={'verbose_name': 'Adresse', 'verbose_name_plural': 'Adresses'},
        ),
        migrations.AlterModelOptions(
            name='companybank',
            options={'verbose_name': 'Information Bancaire', 'verbose_name_plural': 'Informations Bancaires'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Moyen de contact', 'verbose_name_plural': 'Moyens de contact'},
        ),
        migrations.AlterModelOptions(
            name='tiersadresse',
            options={'verbose_name': 'Adresse'},
        ),
        migrations.AddField(
            model_name='tiersadresse',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tiersadresse',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='créer par'),
        ),
        migrations.AddField(
            model_name='tiersadresse',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='créer par'),
        ),
        migrations.AlterField(
            model_name='company',
            name='sigle',
            field=models.CharField(validators=[django.core.validators.MinLengthValidator(3)], verbose_name="Sigle de l'entreprise"),
        ),
        migrations.AlterField(
            model_name='companybank',
            name='account_holder',
            field=models.CharField(help_text='Nom exact figurant sur le relevé bancaire', max_length=150, verbose_name='Titulaire du Compte'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='type_contact',
            field=models.CharField(choices=[('Telephone Mobile', 'Telephone Mobile'), ('Telephone domicile', 'Telephone domicile'), ('email', 'Adresse electronique'), ('fax', 'fax'), ('siteweb', 'Site Web'), ('whatsapp', 'Whatsapp'), ('facebook', 'Facebook'), ('Autre', 'Autre')], max_length=50),
        ),
        migrations.AlterField(
            model_name='phone',
            name='label',
            field=models.CharField(help_text='Ex: Bureau, WhatsApp, Urgence', max_length=50, verbose_name='Étiquette'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='Entrez le numéro au format international (ex: +509 XXXX XXXX pour Haïti ).', max_length=128, region=None, verbose_name='Téléphone'),
        ),
        migrations.AlterField(
            model_name='tiers',
            name='adresse',
            field=models.CharField(max_length=200, verbose_name='Adresse résidentielle'),
        ),
        migrations.AlterField(
            model_name='tiers',
            name='adresse_additionnelle',
            field=models.CharField(blank=True, max_length=200, verbose_name='Adresse Aditionnelle'),
        ),
        migrations.AlterField(
            model_name='tiers',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='créer par'),
        ),
        migrations.AlterField(
            model_name='tiers',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True, verbose_name='Adresse email'),
        ),
        migrations.AlterField(
            model_name='tiers',
            name='genre',
            field=models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin'), ('A', 'Autre')], max_length=1, verbose_name='Genre'),
        ),
        migrations.AlterField(
            model_name='tiers',
            name='niveau_etude',
            field=models.CharField(choices=[('PRIMAIRE', 'Primaire'), ('SECONDAIRE', 'Secondaire'), ('BACC', 'Baccalauréat'), ('DIPLOME', 'Diplome'), ('LICENCE', 'Licence'), ('MASTER', 'Master'), ('DOCTORAT', 'Doctorat'), ('AUTRE', 'Autre')], max_length=20, verbose_name="Niveau d'étude"),
        ),
        migrations.AlterField(
            model_name='tiers',
            name='nombre_enfants',
            field=models.PositiveIntegerField(default=0, verbose_name="Nombre d'enfants"),
        ),
        migrations.AlterField(
            model_name='tiers',
            name='numero_piece',
            field=models.CharField(max_length=50, unique=True, verbose_name='Numéro de pièce'),
        ),
        migrations.AlterField(
            model_name='tiers',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='clients/photos/', verbose_name="Photo d'identite"),
        ),
        migrations.AlterField(
            model_name='tiers',
            name='piece_identite_recto',
            field=models.ImageField(blank=True, null=True, upload_to='clients/pieces_identite/', verbose_name="Recto Pièce d'identité "),
        ),
        migrations.AlterField(
            model_name='tiers',
            name='piece_identite_verso',
            field=models.ImageField(blank=True, null=True, upload_to='clients/pieces_identite/', verbose_name="Pièce d'identité (verso)"),
        ),
        migrations.AlterField(
            model_name='tiers',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='clients/signatures/', verbose_name='Signature'),
        ),
        migrations.AlterField(
            model_name='tiers',
            name='statut_matrimonial',
            field=models.CharField(choices=[('C', 'Célibataire'), ('M', 'Marié(e)'), ('D', 'Divorcé(e)'), ('V', 'Veuf/Veuve'), ('S', 'Séparé(e)')], max_length=1, verbose_name='Statut matrimonial'),
        ),
        migrations.AlterField(
            model_name='tiers',
            name='type_piece_identite',
            field=models.CharField(choices=[('NINU', "Carte  d'Identité Nationale"), ('PASSEPORT', 'Passeport'), ('PERMIS', 'Permis de conduire'), ('NIF', 'Matricule fiscal')], max_length=20, verbose_name="Type de pièce d'identité"),
        ),
        migrations.AlterField(
            model_name='tiersadresse',
            name='type_adresse',
            field=models.CharField(choices=[('Bureau', 'Bureau'), ('Domicile', 'Domicile'), ('Business', 'Business'), ('Livraison', 'Adresse de livraison'), ('Facturation', 'Adresse de facturation')], max_length=50),
        ),
        migrations.AddConstraint(
            model_name='contact',
            constraint=models.UniqueConstraint(fields=('tiers', 'type_contact', 'valeur'), name='unique_contact_par_tiers'),
        ),
    ]
