# Generated by Django 6.0.1 on 2026-02-19 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0003_alter_currency_options'),
        ('societe', '0007_alter_companyaddress_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='parametres.currency'),
        ),
    ]
