# Generated by Django 6.0.1 on 2026-02-19 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('societe', '0009_tiers_religion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiers',
            name='religion',
            field=models.CharField(choices=[('ADVENTISTE', 'Adventiste'), ('CATHOLIQUE', 'Catholique'), ('JEHOVAH', 'Témoin de Jéhovah'), ('MORMON', 'Mormon'), ('MUSULMAN', 'Musulman'), ('PENTECOTISTE', 'Pentecôtiste'), ('PROTESTANT', 'Protestant'), ('VODOUISANT', 'Vodouisant'), ('AUTRE', 'Autre'), ('AUCUNE', 'Aucune / Athée')], max_length=20, null=True, verbose_name='Religion'),
        ),
    ]
