# Generated by Django 6.0.1 on 2026-02-19 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('societe', '0010_alter_tiers_religion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tiers',
            name='adresse',
        ),
        migrations.RemoveField(
            model_name='tiers',
            name='adresse_additionnelle',
        ),
        migrations.RemoveField(
            model_name='tiers',
            name='departement',
        ),
        migrations.RemoveField(
            model_name='tiers',
            name='ville',
        ),
    ]
