# Generated by Django 6.0.1 on 2026-02-19 21:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('societe', '0011_remove_tiers_adresse_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tiers',
            name='numero_piece',
        ),
        migrations.RemoveField(
            model_name='tiers',
            name='type_piece_identite',
        ),
        migrations.AddField(
            model_name='tiers',
            name='type_piece',
            field=models.CharField(choices=[('NINU', " Numéro d'Identification Nationale Unique"), ('PASSEPORT', 'Passeport'), ('PERMIS', 'Permis de conduire'), ('AUTRES', 'AUTRES')], default=django.utils.timezone.now, max_length=20, verbose_name='Type de pièce'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tiers',
            name='religion',
            field=models.CharField(choices=[('BAPTISTE', 'Baptiste'), ('ADVENTISTE', 'Adventiste'), ('CATHOLIQUE', 'Catholique'), ('JEHOVAH', 'Témoin de Jéhovah'), ('MORMON', 'Mormon'), ('MUSULMAN', 'Musulman'), ('PENTECOTISTE', 'Pentecôtiste'), ('PROTESTANT', 'Protestant'), ('VODOUISANT', 'Vodouisant'), ('AUTRE', 'Autre'), ('AUCUNE', 'Aucune / Athée')], max_length=20, null=True, verbose_name='Religion'),
        ),
    ]
