# Generated by Django 6.0.1 on 2026-02-19 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('societe', '0012_remove_tiers_numero_piece_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tiers',
            name='piece_identite_recto',
        ),
        migrations.RemoveField(
            model_name='tiers',
            name='piece_identite_verso',
        ),
        migrations.RemoveField(
            model_name='tiers',
            name='signature',
        ),
        migrations.RemoveField(
            model_name='tiers',
            name='type_piece',
        ),
        migrations.CreateModel(
            name='IdentityDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_piece', models.CharField(choices=[('NINU', "Numéro d'Identification Nationale Unique"), ('PASSEPORT', 'Passeport'), ('PERMIS', 'Permis de conduire'), ('AUTRES', 'AUTRES')], max_length=20, verbose_name='Type de pièce')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='clients/photos/', verbose_name="Photo d'identité (Profil)")),
                ('piece_identite_recto', models.ImageField(blank=True, null=True, upload_to='clients/pieces_identite/', verbose_name='Recto / Page principale')),
                ('piece_identite_verso', models.ImageField(blank=True, null=True, upload_to='clients/pieces_identite/', verbose_name='Verso (laisser vide pour Passeport)')),
                ('signature', models.ImageField(blank=True, null=True, upload_to='clients/signatures/', verbose_name='Signature')),
                ('tiers', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='identity_docs', to='societe.tiers')),
            ],
            options={
                'verbose_name': "Document d'identité",
                'verbose_name_plural': "Documents d'identité",
            },
        ),
    ]
