# Generated by Django 6.0.1 on 2026-02-19 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('societe', '0013_remove_tiers_piece_identite_recto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tiers',
            name='photo',
        ),
    ]
