# Generated by Django 6.0.1 on 2026-03-03 04:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('societe', '0014_remove_tiers_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poste', models.CharField(max_length=100)),
                ('date_embauche', models.DateField()),
                ('salaire_base', models.DecimalField(decimal_places=2, max_digits=15)),
                ('tiers', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employe_data', to='societe.tiers')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employe_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
