# Generated by Django 6.0.1 on 2026-03-03 04:56

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('societe', '0015_employe'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 3, 3, 4, 56, 27, 621386, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employe',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='créer par'),
        ),
        migrations.AddField(
            model_name='employe',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
