# Generated by Django 6.0.1 on 2026-03-03 05:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('societe', '0016_employe_created_at_employe_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employe',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='employe',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='employe',
            name='salaire_base',
        ),
        migrations.RemoveField(
            model_name='employe',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='employe',
            name='est_approbateur',
            field=models.BooleanField(default=False, verbose_name="Droit d'approbation"),
        ),
        migrations.AlterField(
            model_name='employe',
            name='tiers',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='profil_employe', to='societe.tiers'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
