# Generated by Django 6.0.1 on 2026-03-03 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('societe', '0017_remove_employe_created_at_remove_employe_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employe',
            name='user',
        ),
    ]
