# Generated by Django 6.0.1 on 2026-03-03 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('societe', '0019_employe_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='poste',
            field=models.ForeignKey(help_text='Sélectionnez le groupe qui définit les permissions de cet employé', on_delete=django.db.models.deletion.PROTECT, to='auth.group', verbose_name="Poste / Groupe d'accès"),
        ),
    ]
