# Generated by Django 6.0.1 on 2026-03-03 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('societe', '0020_alter_employe_poste'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employe',
            name='poste',
        ),
        migrations.AddField(
            model_name='employe',
            name='postes',
            field=models.ManyToManyField(help_text='Maintenez CTRL pour en sélectionner plusieurs', to='auth.group', verbose_name="Postes / Groupes d'accès"),
        ),
    ]
