# Generated by Django 6.0.1 on 2026-03-03 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('societe', '0021_remove_employe_poste_employe_postes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employe',
            old_name='postes',
            new_name='poste',
        ),
    ]
