# Generated by Django 6.0.1 on 2026-03-03 19:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('societe', '0022_rename_postes_employe_poste'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employe',
            options={'verbose_name': 'Employé', 'verbose_name_plural': 'Employés'},
        ),
        migrations.AlterField(
            model_name='employe',
            name='date_embauche',
            field=models.DateField(verbose_name="Date d'embauche"),
        ),
        migrations.AlterField(
            model_name='employe',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Compte Utilisateur'),
        ),
    ]
