# Generated by Django 6.0.1 on 2026-03-04 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('societe', '0023_alter_employe_options_alter_employe_date_embauche_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='doit_changer_mot_de_passe',
            field=models.BooleanField(default=True, verbose_name='Doit changer de MDP'),
        ),
    ]
