# Generated by Django 6.0.1 on 2026-03-04 22:23

import datetime
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('societe', '0024_employe_doit_changer_mot_de_passe'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 3, 4, 22, 23, 26, 40525, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employe',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employes_crees', to=settings.AUTH_USER_MODEL, verbose_name='créer par'),
        ),
        migrations.AddField(
            model_name='employe',
            name='salaire_base',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Le salaire doit être supérieur à 0.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AddField(
            model_name='employe',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='employe',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='profil_employe', to=settings.AUTH_USER_MODEL, verbose_name='Compte Utilisateur'),
        ),
    ]
