# Generated by Django 6.0.1 on 2026-03-05 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('societe', '0025_employe_created_at_employe_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='créer le'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Modifiier le'),
        ),
    ]
