# Generated by Django 6.0.1 on 2026-03-05 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('societe', '0026_alter_employe_created_at_alter_employe_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiers',
            name='prenoms',
            field=models.CharField(max_length=100, verbose_name='Prénom'),
        ),
    ]
