# Generated by Django 6.0.1 on 2026-03-14 04:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('societe', '0027_alter_tiers_prenoms'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Depense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Motif de la dépense')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date_depense', models.DateField(default=django.utils.timezone.now, verbose_name='Date effective')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Détails supplémentaires')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('employe_responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='depenses_gerees', to='societe.employe', verbose_name='Employé responsable')),
                ('enregistre_par', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='depenses_enregistrees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dépense',
                'verbose_name_plural': 'Dépenses',
                'ordering': ['-date_depense'],
            },
        ),
    ]
