# Generated by Django 6.0.1 on 2026-03-14 15:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('societe', '0029_paiementemploye'),
    ]

    operations = [
        migrations.AddField(
            model_name='identitydocument',
            name='numero_document',
            field=models.CharField(default=datetime.datetime(2026, 3, 14, 15, 32, 35, 74233, tzinfo=datetime.timezone.utc), max_length=50, verbose_name='Numéro de la pièce'),
            preserve_default=False,
        ),
    ]
