# Generated by Django 6.0.1 on 2026-03-14 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('societe', '0030_identitydocument_numero_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identitydocument',
            name='numero_document',
            field=models.CharField(help_text='Ce numéro doit être unique (NIF, CIN ou Passeport)', max_length=50, unique=True, verbose_name='Numéro de la pièce'),
        ),
    ]
