# Generated by Django 6.0.1 on 2026-03-15 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('societe', '0031_alter_identitydocument_numero_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='frais_dossier_pct',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Pourcentage des frais de dossier appliqué à ce client', max_digits=5, verbose_name='Frais de dossier (%)'),
        ),
    ]
