"""
Django settings for ProjectBank project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-h_iw0awgqo%%%gn!8_*oene-nnh=78(bt$5#%t)!xt&@xk0_r@'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'import_export',
    'societe',
    'jet.dashboard',  # Optionnel : pour les graphiques/widgets
    'jet',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'bank',
    'admin_auto_filters',
    'parametres',
    'financier',
    'rapports',
    'smart_selects',
    'django_select2',
]
USE_DJANGO_JQUERY = True  # Pour utiliser le jQuery interne de l'admin

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # AJOUTEZ VOTRE MIDDLEWARE ICI (en bas de la liste)
    'societe.middleware.FirstLoginRedirectMiddleware',
]

ROOT_URLCONF = 'ProjectBank.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ProjectBank.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/


LANGUAGE_CODE = 'fr-fr'
TIME_ZONE = 'America/Port-au-Prince' # Pour avoir l'heure exacte de Port-au-Prince
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_ROOT = '/var/www/gestion_pret/static/'
STATIC_URL = 'static/'

# Assurez-vous que Django sait où chercher votre dossier static à la racine

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]


# Dossier où les fichiers seront réellement stockés sur le disque
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# URL pour accéder à ces fichiers dans le navigateur
MEDIA_URL = '/media/'

# pour choisi couleur theme
JET_DEFAULT_THEME = 'default' # Options: default, green, light-violet, light-blue, light-gray
JET_INDEX_DASHBOARD = 'dashboard.CustomIndexDashboard'

# Configuration Email Gmail
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'jandjsevisfinans@gmail.com'
EMAIL_HOST_PASSWORD = 'jdto ooyp tmjw qsod' # Ne pas utiliser votre mot de passe normal
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

COUNTRIES_FLAG_URL = 'https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.4.3/flags/4x3/{code}.svg'

# Force la redirection vers l'admin après connexion ou reset
LOGIN_URL = '/admin/login/'
LOGIN_REDIRECT_URL = '/admin/'
LOGOUT_REDIRECT_URL = '/admin/login/'

# --- CONFIGURATION DES SESSIONS ---

# 1. La session expire après X secondes d'inactivité (ex: 3600 = 1 heure)
SESSION_COOKIE_AGE = 3600

# 2. Si True, la session expire dès que l'utilisateur ferme son navigateur
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

# 3. IMPORTANT : Met à jour le cookie à chaque requête.
# Si l'utilisateur clique, le décompte repart à zéro (évite de déconnecter un utilisateur actif)
SESSION_SAVE_EVERY_REQUEST = True